language: c

# Once you've nailed down the current warnings, uncomment this:
# env:
#   - global:
#     - WARNINGS_ARE_ERRORS=1

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap

install:
    - ./travis-tool.sh install_deps

# We have to reinstall to use the package
script:
    - ./travis-tool.sh run_tests
    - make install test

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
